# Dependencies
highlighter:      rouge

# Permalinks
permalink:   /:title/

# Setup
title:            electronut
tagline:          Programming & Embedded Systems
description:      Python, OpenGL, and Embedded Systems

url:              https://mkvenkit.github.io
baseurl:          /

author:
  name:           Mahesh Venkitachalam
  url:            https://twitter.com/mkvenkit

paginate:         5

github:
  repo:           https://github.com/mkvenkit
