# Dependencies
highlighter:      rouge

# Permalinks
permalink:   /:title/

# Setup
title:            Electronut
tagline:          'Programming & Embedded Systems'
description:      'Python, OpenGL, & Embedded Systems'

url:              mkvenkit.github.io

baseurl: "/"

home_url: /

author:
  name:           'Mahesh Venkitachalam'
  url:            https://twitter.com/mkvenkit

paginate:         5

github:
  repo:           https://github.com/mkvenkit
