# Setup
title:            electronut
tagline:          Programming & Embedded Systems
description:      Python, OpenGL, and Embedded Systems

url:                 https://mkvenkit.github.io
baseurl:             ''
paginate:            5
permalink:           /:title/

highlighter:      rouge

# About/contact
author:
  name:              Mahesh Venkitachalam
  url:               https://twitter.com/mkvenkit
  email:             info@electronut.in

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
